// Clean, minimal scroll-driven animations
export { default as FadeIn } from './FadeIn'
export { default as HorizontalScroll } from './HorizontalScroll'
export { default as PinSection } from './PinSection'
export { default as SmoothScrollProvider } from './SmoothScrollProvider'
export { default as NumberCounter } from './NumberCounter'
export { default as WordReveal } from './WordReveal'
export { default as CharReveal } from './CharReveal'
export { default as ImageReveal } from './ImageReveal'
export { default as NumberedSection } from './NumberedSection'

// Legacy animations (keep for compatibility)
export { default as SmoothReveal } from './SmoothReveal'
export { default as MagneticButton } from './MagneticButton'
export { default as ParallaxText } from './ParallaxText'
export { default as ScrollVelocity } from './ScrollVelocity'
export { default as SmoothParallax } from './SmoothParallax'
export { default as TextReveal } from './TextReveal'
export { default as ElasticScale } from './ElasticScale'
export { default as CursorFollow } from './CursorFollow'
export { default as Perspective3D } from './Perspective3D'
